---
- name: Preconfig
  host: demo
  vars_files:
  tasks:
    - name: Установка Docker
      block:
        - name: Добавляем universe
          ansible.builtin.apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_destribution_release }} main"
            state: present

        - name: Установка дополнительных пакетов
          apt:
            name: 
              - apt-transport-https 
              - ca-certificates
              - curl 
              - gnupg 
              - lsb-release
            update_cache: yes
            cache_valid_time: 86400

        - name: Добавление ключа Docker
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Установка стабильного репозитория
          ansible.builtin.apt_repository:
            repo: > 
              deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] 
              https://download.docker.com/linux/ubuntu
              {{ ansible_destribution_release }} stable
            state: present
            update_cache: yes
            filename: docker

        - name: Установка docker-ce
          apt:
            name: docker-ce
            update_cache: yes

        - name: Проверка на установленный Docker и его перезагрузка
          ansible.builtin.service:
            name: docker
            state: restarted
            enabled: yes
      become: yes

    - name: Установка Docker-Compose
      block: 
        - name: Получение последней версии Docker-Compose
          ansible.builtin.uri:
            url: https://api.github.com/repos/docker/compose/releases/latest
            body_format: json
          register: page

        - name: Установка Docker-Compose
          ansible.builtin.get_url:
            url: https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64"
            dest: /usr/local/bin/docker-compose
            mode: 0755
      become: yes

    - name: Завершение установки
      block:

        - name: Получение текущего пользователя
          ansible.builtin.shell: "echo $USER"
          register: user


        - name: Добавление пользователя в группу Docker
          user: 
            name: "{{ansible_host_user}}"
            group: docker

        - name: Перезагрузка
          ansible.builtin.reboot:

      become: yes
            



 


