---
- name: Разметка и перенос данных SSD диск
  hosts: jetson_nx
  become: yes
  vars: 
    - disk: /dev/nvme0n1
    - mount_point: /mnt/ssd
    - data_path: /home/user/configuring_kuka_server/ansible/jetson-playbook/partitial-config

  tasks:
    - name: Разметка диска
      block:
        - name: Ensure the disk is present
          command: lsblk {{ disk }}
          register: disk_check
          failed_when: disk_check.rc != 0

        - name: Create a new GPT partition table
          command: parted -s {{ disk }} mklabel gpt

        - name: Create a new primary partition using the entire disk
          command: parted -s {{ disk }} mkpart primary 0% 100%

        - name: Create an Ext4 filesystem on the partition
          command: mkfs.ext4 {{ disk }}p1

        - name: Create the mount point
          file:
            path: "{{ mount_point }}"
            state: directory

        - name: Mount the partition
          mount:
            path: "{{ mount_point }}"
            src: "{{ disk }}p1"
            fstype: ext4
            state: mounted

        - name: Get the UUID of the partition
          command: blkid -s UUID -o value {{ disk }}p1
          register: partition_uuid

        - name: Add the partition to /etc/fstab
          lineinfile:
            path: /etc/fstab
            line: "UUID={{ partition_uuid.stdout }} {{ mount_point }} ext4 defaults 0 2"
            state: present
      become: yes