---
- name: Разметка и перенос данных SSD диск
  hosts: [jetson_nx]
  become: yes
  vars: 
    - partitial_name: nvme0n1
    - partitial_dev: nvme0n1p1
    - data_path: /home/user/configuring_kuka_server/ansible

  tasks:
    - name: Разметка диска
      block:
        - name: Установка рекомендованных пакетов
          apt:
            name:
              - parted
              - e2fsprogs
            state: present
          
        - name: Создание нового раздела
          parted:
            device: "/dev/{{ partitial_name }}"
            number: 1
            state: present
            part_start: 0%
            part_end: 100%
          
        - name: Создание файловой системы раздела
          filesystem:
            fstype: ext4
            dev: "/dev/{{ partitial_dev }}"

        - name: Создание точки монтирования
          file:
            path: "/mnt/{{ partitial_dev }}"
            state: directory

        - name: Монтирование раздела
          mount:
            path: "/mnt/{{ partitial_dev }}"
            src: "/dev/{{ partitial_dev }}"
            fstype: ext4
            state: mounted

        - name: Добавление раздела в fstab
          lineinfile:
            path: /etc/fstab
            line: '/dev/{{ partitial_dev }} /mnt/{{ partitial_dev }} ext4 defaults 0 2'
            state: present
      become: yes

    - name: Перенос данных на диск
      block:
        - name: Создание дирректории /rootOnNVMe
          file:
            path: /rootOnNVMe
            state: directory
            mode: '0755'

        - name: Копирование setup-service.sh в директорию /rootOnNVMe
          copy:
            src: "{{ data_path }}/copy-rootfs-ssd.sh"
            dst: /rootOnNVMe/setup-service.sh
            mode: '0755'
          
        - name: Копирование copy-rootfs-ssd.sh в директорию /rootOnNVMe
          copy:
            src: "{{ data_path }}/copy-rootfs-ssd.sh"
            dst: /rootOnNVMe/copy-rootfs-ssd.sh
            mode: '0755'

        - name: Копирование data/ в директорию /rootOnNVMe
          copy:
            src: "{{ data_path }}/data/"
            dest: /rootOnNVMe/data
            mode: '0755'

        - name: Запуск скрипта copy-rootfs-ssdю.sh
          command:
            cmd: /rootOnNVMe/copy-rootfs-ssd.sh
          args:
            chdir: /rootOnNVMe

        - name: Запуск скрипта setup-service.sh
          command:
            cmd: /rootOnNVMe/setup-service.sh
          args:
            chdir: /rootOnNVMe
